# Generated by Django 3.1.6 on 2021-02-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('Name', 'Type')},
        ),
    ]
